<?php
/**
 * Dummy Data for News & Articles
 *
 * Usage: Automatically runs on init if no articles exist.
 *
 * @package global-tractors
 */

if (!defined('ABSPATH')) exit;

function gti_insert_dummy_news_articles() {
    global $wpdb;
    $table_name = $wpdb->prefix . 'gti_news_articles';

    // Create table if not exists
    $charset_collate = $wpdb->get_charset_collate();

    $create_sql = "CREATE TABLE IF NOT EXISTS {$table_name} (
        id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
        article_id VARCHAR(30) NOT NULL,
        title VARCHAR(255) NOT NULL,
        slug VARCHAR(255) NOT NULL,
        excerpt TEXT,
        content LONGTEXT,
        category VARCHAR(100) NOT NULL DEFAULT 'news',
        tags VARCHAR(500) DEFAULT '',
        author VARCHAR(150) NOT NULL,
        author_email VARCHAR(150) DEFAULT '',
        featured_image VARCHAR(500) DEFAULT '',
        status VARCHAR(20) DEFAULT 'draft',
        views INT DEFAULT 0,
        is_featured TINYINT(1) DEFAULT 0,
        published_at DATETIME DEFAULT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        UNIQUE KEY article_id (article_id),
        KEY status (status),
        KEY category (category),
        KEY author (author),
        KEY created_at (created_at)
    ) {$charset_collate};";
    $wpdb->query($create_sql);

    // Check if data already exists
    $count = $wpdb->get_var("SELECT COUNT(*) FROM {$table_name}");
    if ($count > 0) {
        return;
    }

    $dummy_data = [
        [
            'article_id'      => 'ART-240101',
            'title'           => 'PT Global Tractors Indonesia Resmi Luncurkan Program Loyalti Pelanggan 2024',
            'slug'            => 'pt-global-tractors-indonesia-resmi-luncurkan-program-loyalti-pelanggan-2024',
            'excerpt'         => 'PT Global Tractors Indonesia (GTI) resmi meluncurkan program loyalti baru untuk pelanggan setia, menawarkan berbagai keuntungan eksklusif termasuk diskon spare parts dan prioritas layanan.',
            'content'         => 'PT Global Tractors Indonesia (GTI) secara resmi meluncurkan program loyalti terbaru yang dirancang khusus untuk memberikan apresiasi kepada pelanggan setia. Program ini menawarkan berbagai keuntungan eksklusif, termasuk diskon hingga 15% untuk pembelian spare parts, prioritas layanan purna jual, serta akses eksklusif ke workshop dan pelatihan teknis.\n\nDirektur Utama GTI menyampaikan bahwa program ini merupakan bentuk komitmen perusahaan dalam menjalin hubungan jangka panjang dengan pelanggan. "Kami memahami bahwa kepuasan pelanggan adalah fondasi utama bisnis kami. Melalui program loyalti ini, kami ingin memberikan nilai tambah yang nyata bagi pelanggan yang telah mempercayai produk dan layanan kami," ujarnya.\n\nProgram loyalti ini terdiri dari tiga tingkatan: Silver, Gold, dan Platinum. Setiap tingkatan memiliki benefit yang semakin meningkat, termasuk jaminan suku cadang, layanan darurat 24 jam, hingga undangan ke acara-acara eksklusif GTI.',
            'category'        => 'company-news',
            'tags'            => 'loyalti,pelanggan,promosi,2024',
            'author'          => 'Admin GTI',
            'author_email'    => 'admin@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'published',
            'views'           => 1247,
            'is_featured'     => 1,
            'published_at'    => '2024-01-15 09:00:00',
            'created_at'      => '2024-01-10 14:30:00',
        ],
        [
            'article_id'      => 'ART-240108',
            'title'           => 'Tips Memilih Excavator Bekas yang Berkualitas untuk Proyek Konstruksi',
            'slug'            => 'tips-memilih-excavator-bekas-yang-berkualitas-untuk-proyek-konstruksi',
            'excerpt'         => 'Membeli excavator bekas membutuhkan kehati-hatian. Berikut panduan lengkap untuk memastikan Anda mendapatkan unit yang berkualitas dan sesuai kebutuhan proyek.',
            'content'         => 'Membeli excavator bekas bisa menjadi pilihan cerdas untuk menghemat anggaran proyek, namun diperlukan kehati-hatian dalam memilih. Artikel ini akan membahas tips-tips penting yang perlu diperhatikan sebelum membeli excavator bekas.\n\n1. Periksa Jam Operasi (Hours)\nJam operasi merupakan indikator utama kondisi mesin. Excavator dengan jam operasi di bawah 5.000 jam umumnya masih dalam kondisi baik. Namun, perlu diperhatikan juga bagaimana unit tersebut dirawat selama masa operasinya.\n\n2. Kondisi Hydraulic System\nSistem hidrolik adalah jantung dari setiap excavator. Pastikan tidak ada kebocoran pada hose dan cylinder. Pergerakan boom, arm, dan bucket harus halus tanpa jeda.\n\n3. Kondisi Undercarriage\nUndercarriage merupakan komponen dengan biaya penggantian tertinggi. Periksa ketebalan track shoe, kondisi roller, idler, dan sprocket.\n\n4. Riwayat Perawatan\nMinta riwayat perawatan unit dari pemilik sebelumnya. Unit dengan riwayat perawatan yang teratur biasanya memiliki kondisi yang lebih baik.\n\n5. Uji Coba (Test Run)\nSelalu lakukan uji coba sebelum memutuskan pembelian. Perhatikan performa mesin, responsivitas hidrolik, dan suara-suara tidak wajar.',
            'category'        => 'tips',
            'tags'            => 'excavator,tips,konstruksi,bekas',
            'author'          => 'Tim Teknis GTI',
            'author_email'    => 'teknis@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'published',
            'views'           => 2893,
            'is_featured'     => 1,
            'published_at'    => '2024-01-22 10:00:00',
            'created_at'      => '2024-01-18 11:00:00',
        ],
        [
            'article_id'      => 'ART-240205',
            'title'           => 'GTI Berpartisipasi dalam Indonesia Construction Expo 2024',
            'slug'            => 'gti-berpartisipasi-dalam-indonesia-construction-expo-2024',
            'excerpt'         => 'PT Global Tractors Indonesia turut serta dalam pameran konstruksi terbesar di Indonesia, menampilkan lini produk terbaru dan teknologi canggih untuk industri konstruksi.',
            'content'         => 'PT Global Tractors Indonesia (GTI) sukses berpartisipasi dalam Indonesia Construction Expo 2024 yang digelar di Jakarta Convention Center pada 5-8 Februari 2024.\n\nDalam pameran tahun ini, GTI menampilkan beberapa unit unggulan termasuk excavator seri terbaru, wheel loader, dan bulldozer. Pengunjung berkesempatan untuk melihat langsung demonstrasi fitur-fitur canggih yang dimiliki oleh setiap unit.\n\nSelain pameran unit, GTI juga mengadakan seminar singkat mengenai pentingnya perawatan preventif dan penggunaan teknologi telematik dalam mengoptimalkan produktivitas alat berat.\n\nPameran ini berhasil menarik lebih dari 5.000 pengunjung selama 4 hari pelaksanaan, dengan beberapa kesepakatan bisnis yang terjalin selama acara berlangsung.',
            'category'        => 'event',
            'tags'            => 'pameran,expo,construction,jakarta',
            'author'          => 'Marketing GTI',
            'author_email'    => 'marketing@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'published',
            'views'           => 876,
            'is_featured'     => 0,
            'published_at'    => '2024-02-12 08:00:00',
            'created_at'      => '2024-02-10 16:00:00',
        ],
        [
            'article_id'      => 'ART-240220',
            'title'           => 'Panduan Perawatan Undercarriage Excavator',
            'slug'            => 'panduan-perawatan-undercarriage-excavator',
            'excerpt'         => 'Undercarriage merupakan komponen kritis yang membutuhkan perawatan rutin. Pelajari cara merawat undercarriage excavator agar umur pakai lebih panjang.',
            'content'         => 'Undercarriage excavator merupakan salah satu komponen paling mahal dan kritis. Perawatan yang tepat dapat memperpanjang umur pakai hingga 40% lebih lama.\n\nBerikut panduan perawatan undercarriage yang direkomendasikan:\n\n1. Inspeksi Harian\nPeriksa kondisi track shoe, pastikan tidak ada benda asing yang tersangkut. Perhatikan kebocoran pada carrier roller dan track roller.\n\n2. Pelumasan Rutin\nLumasi semua pin dan bushing sesuai dengan jadwal yang direkomendasikan oleh pabrikan. Gunakan pelumas dengan grade yang sesuai.\n\n3. Pengencangan Track\nPastikan tension track berada pada tingkat yang tepat. Track yang terlalu longgar dapat menyebabkan wheel detachment, sementara yang terlalu ketat meningkatkan keausan.\n\n4. Pembersihan Berkala\nBersihkan undercarriage dari lumpur dan material yang menempel secara berkala. Material yang tertinggal dapat mempercepat keausan komponen.\n\n5. Rotasi Komponen\nLakukan rotasi track shoe secara berkala untuk keausan yang merata. Perhatikan juga kondisi sprocket dan ganti jika sudah aus.',
            'category'        => 'tips',
            'tags'            => 'undercarriage,perawatan,excavator,maintenance',
            'author'          => 'Tim Teknis GTI',
            'author_email'    => 'teknis@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'published',
            'views'           => 1534,
            'is_featured'     => 0,
            'published_at'    => '2024-02-28 09:30:00',
            'created_at'      => '2024-02-25 13:00:00',
        ],
        [
            'article_id'      => 'ART-240310',
            'title'           => 'Analisis Tren Pasar Alat Berat Indonesia 2024',
            'slug'            => 'analisis-tren-pasar-alat-berat-indonesia-2024',
            'excerpt'         => 'Industri alat berat di Indonesia terus menunjukkan pertumbuhan positif. Simak analisis lengkap tren pasar dan peluang bisnis di tahun 2024.',
            'content'         => 'Industri alat berat di Indonesia diproyeksikan mengalami pertumbuhan yang signifikan di tahun 2024, didorong oleh berbagai proyek infrastruktur pemerajat dan aktivitas pertambangan yang meningkat.\n\nBeberapa tren utama yang perlu diperhatikan:\n\n1. Digitalisasi dan IoT\nSemakin banyak perusahaan konstruksi yang mengadopsi teknologi telematik dan IoT untuk memantau kondisi alat berat secara real-time.\n\n2. Pertumbuhan Sektor Pertambangan\nPermintaan alat berat untuk sektor pertambangan terus meningkat, terutama untuk unit-unit berkapasitas besar.\n\n3. Peningkatan Infrastruktur\nProyek-proyek infrastruktur seperti jalan tol, bandara, dan pelabuhan menjadi driver utama pertumbuhan permintaan.\n\n4. Transisi ke Emisi Lebih Rendah\nBeberapa pabrikan mulai memperkenalkan alat berat dengan teknologi mesin yang lebih ramah lingkungan.\n\n5. Pasar Bekas (Used Equipment)\nPasar alat bekas terus diminati karena menawarkan alternatif yang lebih ekonomis tanpa mengorbankan kualitas.',
            'category'        => 'industry',
            'tags'            => 'pasar,alat-berat,tren,indonesia,2024',
            'author'          => 'Riset GTI',
            'author_email'    => 'riset@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'published',
            'views'           => 2156,
            'is_featured'     => 1,
            'published_at'    => '2024-03-15 07:00:00',
            'created_at'      => '2024-03-10 10:00:00',
        ],
        [
            'article_id'      => 'ART-240325',
            'title'           => 'Cara Efektif Meningkatkan Efisiensi Bahan Bakar pada Alat Berat',
            'slug'            => 'cara-efektif-meningkatkan-efisiensi-bahan-bakar-pada-alat-berat',
            'excerpt'         => 'Bahan bakar merupakan salah satu biaya operasional terbesar. Pelajari strategi untuk mengoptimalkan konsumsi bahan bakar pada alat berat Anda.',
            'content'         => 'Bahan bakar merupakan komponen biaya operasional terbesar dalam pengoperasian alat berat, mencakup hingga 30-40% dari total biaya operasional. Oleh karena itu, optimalisasi konsumsi bahan bakar menjadi sangat penting.\n\nStrategi untuk meningkatkan efisiensi bahan bakar:\n\n1. Pelatihan Operator\nOperator yang terampil dapat menghemat bahan bakar hingga 20%. Pelatihan harus mencakup teknik pengoperasian yang efisien.\n\n2. Pemeliharaan Preventif\nMesin yang terawat dengan baik memiliki konsumsi bahan bakar yang lebih optimal. Ganti filter udara dan fuel filter secara berkala.\n\n3. Monitoring Konsumsi\nGunakan sistem telematik untuk memantau konsumsi bahan bakar secara real-time dan mendeteksi penyimpangan.\n\n4. Pengurangan Idle Time\nKurangi waktu idle yang tidak perlu. Idle time yang berlebihan dapat menghabiskan hingga 1 liter bahan bakar per jam.\n\n5. Pemilihan Grade Bahan Bakar\nGunakan grade bahan bakar yang sesuai dengan rekomendasi pabrikan untuk performa mesin optimal.',
            'category'        => 'tips',
            'tags'            => 'bahan-bakar,efisiensi,operasional,biaya',
            'author'          => 'Tim Teknis GTI',
            'author_email'    => 'teknis@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'published',
            'views'           => 1089,
            'is_featured'     => 0,
            'published_at'    => '2024-04-02 08:30:00',
            'created_at'      => '2024-03-28 14:00:00',
        ],
        [
            'article_id'      => 'ART-240415',
            'title'           => 'Workshop Teknisi GTI: Pelatihan Perawatan Hidrolik Level Lanjut',
            'slug'            => 'workshop-teknisi-gti-pelatihan-perawatan-hidrolik-level-lanjut',
            'excerpt'         => 'GTI mengadakan workshop intensif untuk teknisi mitra mengenai perawatan sistem hidrolik alat berat tingkat lanjut.',
            'content'         => 'PT Global Tractors Indonesia (GTI) mengadakan workshop pelatihan intensif tiga hari untuk teknisi-tknisi dari mitra-mitra service center di seluruh Indonesia.\n\nWorkshop yang diadakan di Training Center GTI ini mencakup:\n\n- Diagnosa kerusakan sistem hidrolik menggunakan diagnostic tools modern\n- Perbaikan dan penggantian hydraulic pump\n- Kalibrasi dan setting sistem kontrol hidrolik\n- Troubleshooting kebocoran hidrolik\n- Analisis oil sample untuk deteksi dini kerusakan\n\nWorkshop ini diikuti oleh 25 teknisi dari 12 mitra service center. Para peserta mendapatkan sertifikat competency setelah menyelesaikan ujian praktik dan teori.\n\n"Workshop seperti ini sangat penting untuk meningkatkan kompetensi teknisi kami sehingga dapat memberikan layanan terbaik kepada pelanggan," ujar Manajer Pelatihan GTI.',
            'category'        => 'company-news',
            'tags'            => 'workshop,pelatihan,hidrolik,teknisi',
            'author'          => 'HRD GTI',
            'author_email'    => 'hrd@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'published',
            'views'           => 654,
            'is_featured'     => 0,
            'published_at'    => '2024-04-20 10:00:00',
            'created_at'      => '2024-04-18 09:00:00',
        ],
        [
            'article_id'      => 'ART-240501',
            'title'           => 'Mengenal Teknologi Tier 4 Final pada Alat Berat Modern',
            'slug'            => 'mengenal-teknologi-tier-4-final-pada-alat-berat-modern',
            'excerpt'         => 'Standar emisi Tier 4 Final mulai diterapkan di Indonesia. Pelajari apa itu Tier 4 Final dan bagaimana dampaknya terhadap alat berat.',
            'content'         => 'Standar emisi Tier 4 Final merupakan regulasi yang semakin diterapkan di berbagai negara, termasuk Indonesia. Artikel ini menjelaskan apa itu Tier 4 Final dan dampaknya terhadap industri alat berat.\n\nApa itu Tier 4 Final?\nTier 4 Final adalah standar emisi terketat yang ditetapkan oleh EPA (Environmental Protection Agency) untuk mesin diesel off-road. Standar ini mensyaratkan pengurangan emisi partikulat hingga 90% dan NOx hingga 89% dibandingkan standar Tier 3.\n\nTeknologi utama yang digunakan:\n- Diesel Particulate Filter (DPF)\n- Selective Catalytic Reduction (SCR)\n- Exhaust Gas Recirculation (EGR)\n- Diesel Exhaust Fluid (DEF) / AdBlue\n\nManfaat Tier 4 Final:\n- Emisi yang lebih bersih\n- Efisiensi bahan bakar yang lebih baik\n- Pengurangan biaya operasional jangka panjang\n\nGTI telah menyiapkan lini produk Tier 4 Final untuk memenuhi kebutuhan pelanggan yang mengutamakan kepatuhan regulasi dan kelestarian lingkungan.',
            'category'        => 'industry',
            'tags'            => 'tier4,emisi,regulasi,teknologi,lingkungan',
            'author'          => 'Riset GTI',
            'author_email'    => 'riset@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'draft',
            'views'           => 0,
            'is_featured'     => 0,
            'published_at'    => NULL,
            'created_at'      => '2024-05-05 11:00:00',
        ],
        [
            'article_id'      => 'ART-240510',
            'title'           => 'Strategi Pemilihan Spare Parts Asli vs Aftermarket',
            'slug'            => 'strategi-pemilihan-spare-parts-asli-vs-aftermarket',
            'excerpt'         => 'Memilih antara spare parts asli (OEM) dan aftermarket memerlukan pertimbangan matang. Berikut analisis perbandingan untuk membantu keputusan Anda.',
            'content'         => 'Salah satu keputusan penting dalam pemeliharaan alat berat adalah pemilihan antara spare parts asli (OEM) dan aftermarket. Keduanya memiliki kelebihan dan kekurangan masing-masing.\n\nSpare Parts OEM (Original Equipment Manufacturer):\nKelebihan:\n- Didesain khusus untuk model mesin tertentu\n- Kualitas terjamin sesuai standar pabrikan\n- Garansi resmi dari pabrikan\n- Kompatibilitas sempurna\n\nKekurangan:\n- Harga lebih tinggi\n- Ketersediaan terkadang terbatas\n\nSpare Parts Aftermarket:\nKelebihan:\n- Harga lebih terjangkau\n- Ketersediaan lebih mudah\n- Variasi pilihan lebih banyak\n\nKekurangan:\n- Kualitas bervariasi\n- Tidak ada garansi pabrikan\n- Risiko ketidakkompatibelan\n\nRekomendasi GTI:\nUntuk komponen kritis seperti hydraulic pump, engine parts, dan undercarriage, disarankan menggunakan spare parts OEM. Untuk komponen non-kritis seperti filter, belt, dan lampu, aftermarket berkualitas dapat menjadi alternatif yang baik.',
            'category'        => 'tips',
            'tags'            => 'spare-parts,oem,aftermarket,maintenance',
            'author'          => 'Tim Teknis GTI',
            'author_email'    => 'teknis@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'draft',
            'views'           => 0,
            'is_featured'     => 0,
            'published_at'    => NULL,
            'created_at'      => '2024-05-12 15:00:00',
        ],
        [
            'article_id'      => 'ART-240520',
            'title'           => 'GTI Buka Layanan Service Center Baru di Balikpapan',
            'slug'            => 'gti-buka-layanan-service-center-baru-di-balikpapan',
            'excerpt'         => 'PT Global Tractors Indonesia memperluas jaringan layanan purna jual dengan membuka service center baru di Balikpapan, Kalimantan Timur.',
            'content'         => 'PT Global Tractors Indonesia (GTI) resmi membuka service center baru di kota Balikpapan, Kalimantan Timur. Service center ini merupakan yang ke-8 di Indonesia dan dirancang untuk melayani kebutuhan pelanggan di kawasan Kalimantan.\n\nFasilitas baru ini dilengkapi dengan:\n- Workshop seluas 2.500 m²\n- 4 bay service untuk alat berat berukuran besar\n- 2 bay service untuk alat berat berukuran kecil-menengah\n- Area penyimpanan spare parts seluas 500 m²\n- Ruang training untuk pelatihan teknisi\n- Office area untuk tim service\n\nDengan dibukanya service center ini, GTI berharap dapat memberikan layanan yang lebih cepat dan responsif kepada pelanggan di wilayah Kalimantan, yang selama ini harus menunggu lebih lama untuk mendapatkan layanan purna jual.\n\nService center baru ini mulai beroperasi penuh pada 1 Juni 2024.',
            'category'        => 'company-news',
            'tags'            => 'service-center,balikpapan,kalimantan,ekspansi',
            'author'          => 'Admin GTI',
            'author_email'    => 'admin@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'published',
            'views'           => 432,
            'is_featured'     => 0,
            'published_at'    => '2024-05-25 08:00:00',
            'created_at'      => '2024-05-20 10:30:00',
        ],
        [
            'article_id'      => 'ART-240601',
            'title'           => 'Checklist Lengkap Inspeksi Harian Alat Berat',
            'slug'            => 'checklist-lengkap-inspeksi-harian-alat-berat',
            'excerpt'         => 'Inspeksi harian yang teratur dapat mencegah kerusakan besar dan menghemat biaya perbaikan. Berikut checklist lengkap untuk operator.',
            'content'         => 'Inspeksi harian adalah langkah pertama dalam program pemeliharaan preventif yang efektif. Berikut checklist lengkap yang harus dilakukan operator setiap hari sebelum memulai operasi.\n\nSebelum Start Engine:\n1. Periksa level oli mesin\n2. Periksa level oli hidrolik\n3. Periksa level coolant\n4. Periksa kondisi belt\n5. Periksa level bahan bakar\n6. Periksa kondisi filter udara\n7. Inspeksi visual kebocoran\n\nSaat Start Engine:\n1. Perhatikan suara mesin saat start\n2. Periksa tekanan oli pada dashboard\n3. Periksa temperature mesin\n4. Test semua fungsi lampu\n5. Test fungsi alarm dan safety device\n\nSaat Operasi:\n1. Perhatikan performa mesin\n2. Perhatikan suhu kerja\n3. Perhatikan suara abnormal\n4. Monitor konsumsi bahan bakar\n\nSetelah Operasi:\n1. Bersihkan unit dari material\n2. Periksa kembali level fluida\n3. Catat jam operasi\n4. Laporkan keluhan atau anomali\n\nChecklist ini harus diisi dan disimpan sebagai dokumentasi pemeliharaan.',
            'category'        => 'tips',
            'tags'            => 'checklist,inspeksi,harian,operator,maintenance',
            'author'          => 'Tim Teknis GTI',
            'author_email'    => 'teknis@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'published',
            'views'           => 3421,
            'is_featured'     => 0,
            'published_at'    => '2024-06-05 09:00:00',
            'created_at'      => '2024-06-01 14:00:00',
        ],
        [
            'article_id'      => 'ART-240615',
            'title'           => 'Rilis Produk Baru: Komatsu PC210LC-11 dengan Teknologi KOMTRAX',
            'slug'            => 'rilis-produk-baru-komatsu-pc210lc-11-dengan-teknologi-komtrax',
            'excerpt'         => 'GTI memperkenalkan excavator terbaru Komatsu PC210LC-11 yang dilengkapi dengan teknologi pemantauan jarak jauh KOMTRAX.',
            'content'         => 'PT Global Tractors Indonesia dengan bangga memperkenalkan unit terbaru dari lini excavator mereka, yaitu Komatsu PC210LC-11 yang dilengkapi dengan teknologi pemantauan jarak jauh KOMTRAX.\n\nFitur unggulan Komatsu PC210LC-11:\n\n1. Mesin Komatsu SAA6D107E-3\n- Tenaga mesin 155 HP\n- Konsumsi bahan bakar 15% lebih efisien dari pendahulunya\n- Memenuhi standar emisi Tier 4 Final\n\n2. Teknologi KOMTRAX\n- Pemantauan lokasi unit secara real-time\n- Monitoring konsumsi bahan bakar\n- Alert kondisi mesin dan komponen\n- Laporan produktivitas otomatis\n\n3. Kenyamanan Operator\n- Kabin yang lebih luas dan ergonomis\n- AC dengan pendingin lebih baik\n- Visibilitas optimal dengan kamera 360°\n\n4. Kemudahan Perawatan\n- Akses yang mudah untuk inspeksi harian\n- Interval perawatan yang lebih panjang\n- Sistem pelumasan otomatis\n\nHarga spesial peluncuran tersedia untuk pemesanan hingga akhir Juni 2024. Hubungi sales representative GTI untuk informasi lebih lanjut.',
            'category'        => 'product',
            'tags'            => 'komatsu,pc210,komtrax,excavater,produk-baru',
            'author'          => 'Product GTI',
            'author_email'    => 'product@global-tractors.co.id',
            'featured_image'  => '',
            'status'          => 'published',
            'views'           => 1876,
            'is_featured'     => 1,
            'published_at'    => '2024-06-20 07:00:00',
            'created_at'      => '2024-06-15 11:00:00',
        ],
    ];

    foreach ($dummy_data as $item) {
        $wpdb->insert($table_name, $item);
    }
}
