<?php
/**
 * Dummy Data for Equipment (gti_equipment table)
 *
 * Inserts sample equipment data matching the dashboard template.
 * Run via admin_init or wp-cli; safe to call multiple times (checks for existing data).
 *
 * @package global-tractors
 */

if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Insert dummy equipment data into gti_equipment table.
 */
function gti_insert_dummy_equipment() {
    global $wpdb;
    $table = $wpdb->prefix . 'gti_equipment';

    // Check if table exists
    $table_exists = $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $table ) );
    if ( ! $table_exists ) {
        return;
    }

    // Check if data already exists
    $count = (int) $wpdb->get_var( "SELECT COUNT(*) FROM {$table}" );
    if ( $count > 0 ) {
        return;
    }

    $equipment = gti_get_dummy_equipment_data();

    foreach ( $equipment as $item ) {
        $wpdb->insert( $table, [
            'equipment_code'   => $item['equipment_code'],
            'name'             => $item['name'],
            'type'             => $item['type'],
            'category'         => $item['category'],
            'brand'            => $item['brand'],
            'model'            => $item['model'],
            'year'             => $item['year'],
            'condition_status' => $item['condition_status'],
            'status'           => $item['status'],
            'price'            => $item['price'],
            'price_type'       => 'sale',
            'location'         => $item['location'],
            'hours'            => $item['hours'],
            'description'      => $item['description'],
            'main_image'       => $item['main_image'],
            'negotiable'       => 1,
            'created_at'       => current_time( 'mysql' ),
            'updated_at'       => current_time( 'mysql' ),
        ] );
    }
}

/**
 * Return dummy equipment data as an array.
 * Used as fallback when gti_equipment table is empty or missing.
 *
 * @return array
 */
function gti_get_dummy_equipment_data() {
    return [
        [
            'equipment_code'   => 'GTI-EXC-001',
            'name'             => 'KOMATSU PC200-8',
            'type'             => 'used',
            'category'         => 'Excavator',
            'brand'            => 'KOMATSU',
            'model'            => 'PC200-8',
            'year'             => 2020,
            'condition_status' => 'Excellent',
            'status'           => 'available',
            'price'            => 850000000,
            'location'         => 'Balikpapan',
            'hours'            => 5200,
            'description'      => 'KOMATSU PC200-8 excavator in excellent condition. Low hours, well maintained.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-EXC-002',
            'name'             => 'CAT 320D',
            'type'             => 'used',
            'category'         => 'Excavator',
            'brand'            => 'CATERPILLAR',
            'model'            => '320D',
            'year'             => 2019,
            'condition_status' => 'Good',
            'status'           => 'available',
            'price'            => 720000000,
            'location'         => 'Samarinda',
            'hours'            => 8100,
            'description'      => 'CATERPILLAR 320D excavator. Good working condition, ready for deployment.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-BLD-001',
            'name'             => 'KOMATSU D65PX-18',
            'type'             => 'used',
            'category'         => 'Bulldozer',
            'brand'            => 'KOMATSU',
            'model'            => 'D65PX-18',
            'year'             => 2021,
            'condition_status' => 'Excellent',
            'status'           => 'sold',
            'price'            => 1200000000,
            'location'         => 'Banjarmasin',
            'hours'            => 3800,
            'description'      => 'KOMATSU D65PX-18 bulldozer. Excellent condition, low hours.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-WLD-001',
            'name'             => 'CAT 950GC',
            'type'             => 'used',
            'category'         => 'Wheel Loader',
            'brand'            => 'CATERPILLAR',
            'model'            => '950GC',
            'year'             => 2022,
            'condition_status' => 'Good',
            'status'           => 'reserved',
            'price'            => 980000000,
            'location'         => 'Palangkaraya',
            'hours'            => 2500,
            'description'      => 'CATERPILLAR 950GC wheel loader. Good condition, currently reserved.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-EXC-003',
            'name'             => 'HITACHI ZX210LCH-5A',
            'type'             => 'used',
            'category'         => 'Excavator',
            'brand'            => 'HITACHI',
            'model'            => 'ZX210LCH-5A',
            'year'             => 2020,
            'condition_status' => 'Fair',
            'status'           => 'available',
            'price'            => 780000000,
            'location'         => 'Pontianak',
            'hours'            => 6400,
            'description'      => 'HITACHI ZX210LCH-5A excavator. Fair condition, operational.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-EXC-004',
            'name'             => 'VOLVO EC210D',
            'type'             => 'used',
            'category'         => 'Excavator',
            'brand'            => 'VOLVO',
            'model'            => 'EC210D',
            'year'             => 2021,
            'condition_status' => 'Excellent',
            'status'           => 'available',
            'price'            => 920000000,
            'location'         => 'Balikpapan',
            'hours'            => 3200,
            'description'      => 'VOLVO EC210D excavator. Excellent condition, premium machine.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-EXC-005',
            'name'             => 'DOOSAN DX225LC',
            'type'             => 'used',
            'category'         => 'Excavator',
            'brand'            => 'DOOSAN',
            'model'            => 'DX225LC',
            'year'             => 2019,
            'condition_status' => 'Good',
            'status'           => 'available',
            'price'            => 680000000,
            'location'         => 'Samarinda',
            'hours'            => 7500,
            'description'      => 'DOOSAN DX225LC excavator. Good condition, reliable performer.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-DMP-001',
            'name'             => 'HINO FM 350',
            'type'             => 'used',
            'category'         => 'Dump Truck',
            'brand'            => 'HINO',
            'model'            => 'FM 350',
            'year'             => 2020,
            'condition_status' => 'Good',
            'status'           => 'available',
            'price'            => 650000000,
            'location'         => 'Banjarbaru',
            'hours'            => 4800,
            'description'      => 'HINO FM 350 dump truck. Good condition, ready for heavy duty.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-EXC-006',
            'name'             => 'KOMATSU PC300-8',
            'type'             => 'used',
            'category'         => 'Excavator',
            'brand'            => 'KOMATSU',
            'model'            => 'PC300-8',
            'year'             => 2018,
            'condition_status' => 'Fair',
            'status'           => 'available',
            'price'            => 1100000000,
            'location'         => 'Balikpapan',
            'hours'            => 9200,
            'description'      => 'KOMATSU PC300-8 large excavator. Fair condition, high hours but operational.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-CRN-001',
            'name'             => 'KATO KR-25H',
            'type'             => 'used',
            'category'         => 'Crane',
            'brand'            => 'KATO',
            'model'            => 'KR-25H',
            'year'             => 2019,
            'condition_status' => 'Good',
            'status'           => 'available',
            'price'            => 850000000,
            'location'         => 'Samarinda',
            'hours'            => 5100,
            'description'      => 'KATO KR-25H crane. Good condition, ready for lifting operations.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-BLD-002',
            'name'             => 'CAT D6T',
            'type'             => 'used',
            'category'         => 'Bulldozer',
            'brand'            => 'CATERPILLAR',
            'model'            => 'D6T',
            'year'             => 2020,
            'condition_status' => 'Excellent',
            'status'           => 'available',
            'price'            => 1350000000,
            'location'         => 'Palangkaraya',
            'hours'            => 4200,
            'description'      => 'CATERPILLAR D6T bulldozer. Excellent condition, low hours.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-FKL-001',
            'name'             => 'TOYOTA 8FGU25',
            'type'             => 'used',
            'category'         => 'Forklift',
            'brand'            => 'TOYOTA',
            'model'            => '8FGU25',
            'year'             => 2021,
            'condition_status' => 'Excellent',
            'status'           => 'available',
            'price'            => 180000000,
            'location'         => 'Banjarmasin',
            'hours'            => 2100,
            'description'      => 'TOYOTA 8FGU25 forklift. Excellent condition, like new.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-GRD-001',
            'name'             => 'KOMATSU GD655',
            'type'             => 'used',
            'category'         => 'Motor Grader',
            'brand'            => 'KOMATSU',
            'model'            => 'GD655',
            'year'             => 2018,
            'condition_status' => 'Fair',
            'status'           => 'available',
            'price'            => 950000000,
            'location'         => 'Pontianak',
            'hours'            => 8500,
            'description'      => 'KOMATSU GD655 motor grader. Fair condition, proven performer.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-WLD-002',
            'name'             => 'SDLG LG936L',
            'type'             => 'used',
            'category'         => 'Wheel Loader',
            'brand'            => 'SDLG',
            'model'            => 'LG936L',
            'year'             => 2022,
            'condition_status' => 'Excellent',
            'status'           => 'available',
            'price'            => 520000000,
            'location'         => 'Banjarbaru',
            'hours'            => 1800,
            'description'      => 'SDLG LG936L wheel loader. Excellent condition, almost new.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-EXC-007',
            'name'             => 'SANY SY215C',
            'type'             => 'used',
            'category'         => 'Excavator',
            'brand'            => 'SANY',
            'model'            => 'SY215C',
            'year'             => 2021,
            'condition_status' => 'Good',
            'status'           => 'available',
            'price'            => 620000000,
            'location'         => 'Balikpapan',
            'hours'            => 4500,
            'description'      => 'SANY SY215C excavator. Good condition, competitive pricing.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-DMP-002',
            'name'             => 'HINO FG 235',
            'type'             => 'used',
            'category'         => 'Dump Truck',
            'brand'            => 'HINO',
            'model'            => 'FG 235',
            'year'             => 2019,
            'condition_status' => 'Fair',
            'status'           => 'available',
            'price'            => 480000000,
            'location'         => 'Samarinda',
            'hours'            => 6200,
            'description'      => 'HINO FG 235 dump truck. Fair condition, workhorse vehicle.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-EXC-008',
            'name'             => 'XCMG XE215DA',
            'type'             => 'used',
            'category'         => 'Excavator',
            'brand'            => 'XCMG',
            'model'            => 'XE215DA',
            'year'             => 2022,
            'condition_status' => 'Excellent',
            'status'           => 'coming_soon',
            'price'            => 580000000,
            'location'         => 'Balikpapan',
            'hours'            => 1200,
            'description'      => 'XCMG XE215DA excavator. Coming soon, barely used.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-BLD-003',
            'name'             => 'KOMATSU D85PX-18',
            'type'             => 'used',
            'category'         => 'Bulldozer',
            'brand'            => 'KOMATSU',
            'model'            => 'D85PX-18',
            'year'             => 2017,
            'condition_status' => 'Good',
            'status'           => 'available',
            'price'            => 1050000000,
            'location'         => 'Palangkaraya',
            'hours'            => 10200,
            'description'      => 'KOMATSU D85PX-18 bulldozer. Good condition despite higher hours.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-WLD-003',
            'name'             => 'VOLVO L90H',
            'type'             => 'used',
            'category'         => 'Wheel Loader',
            'brand'            => 'VOLVO',
            'model'            => 'L90H',
            'year'             => 2020,
            'condition_status' => 'Excellent',
            'status'           => 'available',
            'price'            => 1050000000,
            'location'         => 'Banjarmasin',
            'hours'            => 3900,
            'description'      => 'VOLVO L90H wheel loader. Excellent condition, premium quality.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-EXC-009',
            'name'             => 'KOBELCO SK200-10',
            'type'             => 'used',
            'category'         => 'Excavator',
            'brand'            => 'KOBELCO',
            'model'            => 'SK200-10',
            'year'             => 2020,
            'condition_status' => 'Good',
            'status'           => 'sold',
            'price'            => 810000000,
            'location'         => 'Pontianak',
            'hours'            => 5800,
            'description'      => 'KOBELCO SK200-10 excavator. Sold, was in good condition.',
            'main_image'       => '',
        ],
        [
            'equipment_code'   => 'GTI-GRD-002',
            'name'             => 'CAT 140M',
            'type'             => 'used',
            'category'         => 'Motor Grader',
            'brand'            => 'CATERPILLAR',
            'model'            => '140M',
            'year'             => 2019,
            'condition_status' => 'Good',
            'status'           => 'available',
            'price'            => 1150000000,
            'location'         => 'Samarinda',
            'hours'            => 7200,
            'description'      => 'CATERPILLAR 140M motor grader. Good condition, precision grading.',
            'main_image'       => '',
        ],
    ];
}
