<?php
/**
 * Dummy Data for Customers
 *
 * Usage: Automatically runs on admin_init if no customers exist.
 *
 * @package global-tractors
 */

if (!defined('ABSPATH')) exit;

function gti_insert_dummy_customers() {
    global $wpdb;
    $table_name = $wpdb->prefix . 'gti_customers';

    // Create table if not exists (use raw query for reliability)
    $charset_collate = $wpdb->get_charset_collate();

    // Check if old table exists with wrong schema — drop and recreate
    $has_city = $wpdb->get_var("SHOW COLUMNS FROM {$table_name} LIKE 'city'");
    if (!$has_city && $wpdb->get_var("SHOW TABLES LIKE '{$table_name}'") === $table_name) {
        $wpdb->query("DROP TABLE IF EXISTS {$table_name}");
    }

    $create_sql = "CREATE TABLE IF NOT EXISTS {$table_name} (
        id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
        customer_id VARCHAR(30) NOT NULL,
        name VARCHAR(150) NOT NULL,
        email VARCHAR(150) NOT NULL,
        phone VARCHAR(50) DEFAULT '',
        company VARCHAR(200) DEFAULT '',
        industry VARCHAR(100) DEFAULT '',
        city VARCHAR(100) DEFAULT '',
        province VARCHAR(100) DEFAULT '',
        country VARCHAR(100) DEFAULT 'Indonesia',
        address TEXT,
        website VARCHAR(200) DEFAULT '',
        npwp VARCHAR(50) DEFAULT '',
        contact_person VARCHAR(150) DEFAULT '',
        contact_position VARCHAR(100) DEFAULT '',
        contact_phone VARCHAR(50) DEFAULT '',
        contact_email VARCHAR(150) DEFAULT '',
        contact_whatsapp VARCHAR(50) DEFAULT '',
        avatar_url VARCHAR(500) DEFAULT '',
        status VARCHAR(20) DEFAULT 'active',
        rating DECIMAL(3,1) DEFAULT 0,
        total_transactions INT DEFAULT 0,
        total_spent BIGINT DEFAULT 0,
        registered_date DATETIME DEFAULT CURRENT_TIMESTAMP,
        last_contact DATETIME,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        UNIQUE KEY customer_id (customer_id),
        KEY status (status),
        KEY email (email),
        KEY company (company),
        KEY registered_date (registered_date)
    ) {$charset_collate};";
    $wpdb->query($create_sql);

    // Check if data already exists
    $count = $wpdb->get_var("SELECT COUNT(*) FROM {$table_name}");
    if ($count > 0) {
        return;
    }

    $dummy_data = [
        [
            'customer_id'         => 'CUST-230112',
            'name'                => 'Budi Santoso',
            'email'               => 'budi@ptabadi.com',
            'phone'               => '+62 812-3456-7890',
            'company'             => 'PT Abadi Sentosa',
            'industry'            => 'Construction',
            'city'                => 'Jakarta',
            'province'            => 'DKI Jakarta',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Jend. Sudirman No. 52, Jakarta Selatan, DKI Jakarta 12190',
            'website'             => 'www.ptabadi.com',
            'npwp'                => '01.234.567.8-009.000',
            'contact_person'      => 'Budi Santoso',
            'contact_position'    => 'Project Manager',
            'contact_phone'       => '+62 812-3456-7890',
            'contact_email'       => 'budi@ptabadi.com',
            'contact_whatsapp'    => '+62 812-3456-7890',
            'status'              => 'active',
            'rating'              => 4.8,
            'total_transactions'  => 12,
            'total_spent'         => 2450750000,
            'registered_date'     => '2023-01-12 09:00:00',
            'last_contact'        => '2024-05-31 10:25:00',
        ],
        [
            'customer_id'         => 'CUST-230215',
            'name'                => 'Siti Rahayu',
            'email'               => 'siti@makmursejahtera.co.id',
            'phone'               => '+62 811-8765-4321',
            'company'             => 'PT Makmur Sejahtera',
            'industry'            => 'Mining',
            'city'                => 'Surabaya',
            'province'            => 'Jawa Timur',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Pemuda No. 33, Surabaya, Jawa Timur 60275',
            'website'             => 'www.makmursejahtera.co.id',
            'npwp'                => '02.345.678.9-010.000',
            'contact_person'      => 'Siti Rahayu',
            'contact_position'    => 'Procurement Manager',
            'contact_phone'       => '+62 811-8765-4321',
            'contact_email'       => 'siti@makmursejahtera.co.id',
            'contact_whatsapp'    => '+62 811-8765-4321',
            'status'              => 'active',
            'rating'              => 4.5,
            'total_transactions'  => 8,
            'total_spent'         => 1875000000,
            'registered_date'     => '2023-02-15 10:30:00',
            'last_contact'        => '2024-05-28 14:15:00',
        ],
        [
            'customer_id'         => 'CUST-230318',
            'name'                => 'Ahmad Hidayat',
            'email'               => 'ahmad@karyamandiri.com',
            'phone'               => '+62 813-9988-7766',
            'company'             => 'CV Karya Mandiri',
            'industry'            => 'Construction',
            'city'                => 'Bandung',
            'province'            => 'Jawa Barat',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Asia Afrika No. 88, Bandung, Jawa Barat 40261',
            'website'             => 'www.karyamandiri.com',
            'npwp'                => '03.456.789.0-011.000',
            'contact_person'      => 'Ahmad Hidayat',
            'contact_position'    => 'Direktur',
            'contact_phone'       => '+62 813-9988-7766',
            'contact_email'       => 'ahmad@karyamandiri.com',
            'contact_whatsapp'    => '+62 813-9988-7766',
            'status'              => 'active',
            'rating'              => 4.2,
            'total_transactions'  => 5,
            'total_spent'         => 980000000,
            'registered_date'     => '2023-03-18 08:00:00',
            'last_contact'        => '2024-05-20 11:08:00',
        ],
        [
            'customer_id'         => 'CUST-230422',
            'name'                => 'Dewi Kusuma',
            'email'               => 'dewi@deltaconstruction.com',
            'phone'               => '+62 817-2233-4455',
            'company'             => 'PT Delta Construction',
            'industry'            => 'Infrastructure',
            'city'                => 'Semarang',
            'province'            => 'Jawa Tengah',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Pandanaran No. 15, Semarang, Jawa Tengah 50241',
            'website'             => 'www.deltaconstruction.com',
            'npwp'                => '04.567.890.1-012.000',
            'contact_person'      => 'Dewi Kusuma',
            'contact_position'    => 'Operations Director',
            'contact_phone'       => '+62 817-2233-4455',
            'contact_email'       => 'dewi@deltaconstruction.com',
            'contact_whatsapp'    => '+62 817-2233-4455',
            'status'              => 'active',
            'rating'              => 4.9,
            'total_transactions'  => 15,
            'total_spent'         => 3250000000,
            'registered_date'     => '2023-04-22 07:30:00',
            'last_contact'        => '2024-05-25 09:45:00',
        ],
        [
            'customer_id'         => 'CUST-230510',
            'name'                => 'Eko Prasetyo',
            'email'               => 'eko@nusantarajaya.co.id',
            'phone'               => '+62 819-5544-3322',
            'company'             => 'PT Nusantara Jaya',
            'industry'            => 'Mining',
            'city'                => 'Balikpapan',
            'province'            => 'Kalimantan Timur',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Jenderal Ahmad Yani No. 10, Balikpapan, Kalimantan Timur 76111',
            'website'             => 'www.nusantarajaya.co.id',
            'npwp'                => '05.678.901.2-013.000',
            'contact_person'      => 'Eko Prasetyo',
            'contact_position'    => 'Fleet Manager',
            'contact_phone'       => '+62 819-5544-3322',
            'contact_email'       => 'eko@nusantarajaya.co.id',
            'contact_whatsapp'    => '+62 819-5544-3322',
            'status'              => 'active',
            'rating'              => 3.8,
            'total_transactions'  => 3,
            'total_spent'         => 520000000,
            'registered_date'     => '2023-05-10 11:00:00',
            'last_contact'        => '2024-04-15 16:30:00',
        ],
        [
            'customer_id'         => 'CUST-230605',
            'name'                => 'Maya Indah',
            'email'               => 'maya@sinarterang.com',
            'phone'               => '+62 815-6677-8899',
            'company'             => 'PT Sinar Terang',
            'industry'            => 'Construction',
            'city'                => 'Yogyakarta',
            'province'            => 'DI Yogyakarta',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Malioboro No. 27, Yogyakarta, DI Yogyakarta 55211',
            'website'             => 'www.sinarterang.com',
            'npwp'                => '06.789.012.3-014.000',
            'contact_person'      => 'Maya Indah',
            'contact_position'    => 'Project Coordinator',
            'contact_phone'       => '+62 815-6677-8899',
            'contact_email'       => 'maya@sinarterang.com',
            'contact_whatsapp'    => '+62 815-6677-8899',
            'status'              => 'inactive',
            'rating'              => 4.0,
            'total_transactions'  => 2,
            'total_spent'         => 350000000,
            'registered_date'     => '2023-06-05 13:00:00',
            'last_contact'        => '2024-03-10 08:20:00',
        ],
        [
            'customer_id'         => 'CUST-230720',
            'name'                => 'Fajar Nugroho',
            'email'               => 'fajar@cahayabaru.co.id',
            'phone'               => '+62 821-1122-3344',
            'company'             => 'CV Cahaya Baru',
            'industry'            => 'Infrastructure',
            'city'                => 'Malang',
            'province'            => 'Jawa Timur',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Basuki Rahmat No. 45, Malang, Jawa Timur 65111',
            'website'             => 'www.cahayabaru.co.id',
            'npwp'                => '07.890.123.4-015.000',
            'contact_person'      => 'Fajar Nugroho',
            'contact_position'    => 'Site Manager',
            'contact_phone'       => '+62 821-1122-3344',
            'contact_email'       => 'fajar@cahayabaru.co.id',
            'contact_whatsapp'    => '+62 821-1122-3344',
            'status'              => 'active',
            'rating'              => 4.6,
            'total_transactions'  => 7,
            'total_spent'         => 1425000000,
            'registered_date'     => '2023-07-20 09:15:00',
            'last_contact'        => '2024-05-18 10:00:00',
        ],
        [
            'customer_id'         => 'CUST-230814',
            'name'                => 'Lestari Wijaya',
            'email'               => 'lestari@grahainvestama.com',
            'phone'               => '+62 823-4455-6677',
            'company'             => 'PT Graha Investama',
            'industry'            => 'Construction',
            'city'                => 'Medan',
            'province'            => 'Sumatera Utara',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Pemuda No. 12, Medan, Sumatera Utara 20231',
            'website'             => 'www.grahainvestama.com',
            'npwp'                => '08.901.234.5-016.000',
            'contact_person'      => 'Lestari Wijaya',
            'contact_position'    => 'Technical Manager',
            'contact_phone'       => '+62 823-4455-6677',
            'contact_email'       => 'lestari@grahainvestama.com',
            'contact_whatsapp'    => '+62 823-4455-6677',
            'status'              => 'active',
            'rating'              => 4.3,
            'total_transactions'  => 6,
            'total_spent'         => 1150000000,
            'registered_date'     => '2023-08-14 14:00:00',
            'last_contact'        => '2024-05-22 13:15:00',
        ],
        [
            'customer_id'         => 'CUST-230901',
            'name'                => 'Rizky Pratama',
            'email'               => 'rizky@berkahjaya.co.id',
            'phone'               => '+62 816-7788-9900',
            'company'             => 'PT Berkah Jaya',
            'industry'            => 'Mining',
            'city'                => 'Pontianak',
            'province'            => 'Kalimantan Barat',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Gajah Mada No. 7, Pontianak, Kalimantan Barat 78111',
            'website'             => 'www.berkahjaya.co.id',
            'npwp'                => '09.012.345.6-017.000',
            'contact_person'      => 'Rizky Pratama',
            'contact_position'    => 'Procurement Lead',
            'contact_phone'       => '+62 816-7788-9900',
            'contact_email'       => 'rizky@berkahjaya.co.id',
            'contact_whatsapp'    => '+62 816-7788-9900',
            'status'              => 'active',
            'rating'              => 4.7,
            'total_transactions'  => 9,
            'total_spent'         => 2100000000,
            'registered_date'     => '2023-09-01 08:45:00',
            'last_contact'        => '2024-05-30 15:00:00',
        ],
        [
            'customer_id'         => 'CUST-231018',
            'name'                => 'Putri Anjani',
            'email'               => 'putri@mitrakonstruksi.com',
            'phone'               => '+62 822-3344-5566',
            'company'             => 'CV Mitra Konstruksi',
            'industry'            => 'Construction',
            'city'                => 'Makassar',
            'province'            => 'Sulawesi Selatan',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Pettarani No. 20, Makassar, Sulawesi Selatan 90221',
            'website'             => 'www.mitrakonstruksi.com',
            'npwp'                => '10.123.456.7-018.000',
            'contact_person'      => 'Putri Anjani',
            'contact_position'    => 'General Manager',
            'contact_phone'       => '+62 822-3344-5566',
            'contact_email'       => 'putri@mitrakonstruksi.com',
            'contact_whatsapp'    => '+62 822-3344-5566',
            'status'              => 'active',
            'rating'              => 4.1,
            'total_transactions'  => 4,
            'total_spent'         => 780000000,
            'registered_date'     => '2023-10-18 10:30:00',
            'last_contact'        => '2024-04-28 09:00:00',
        ],
        [
            'customer_id'         => 'CUST-231105',
            'name'                => 'Hendra Wijaya',
            'email'               => 'hendra@ciptabangun.co.id',
            'phone'               => '+62 818-2233-4455',
            'company'             => 'PT Cipta Bangun',
            'industry'            => 'Infrastructure',
            'city'                => 'Palembang',
            'province'            => 'Sumatera Selatan',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Merdeka No. 55, Palembang, Sumatera Selatan 30121',
            'website'             => 'www.ciptabangun.co.id',
            'npwp'                => '11.234.567.8-019.000',
            'contact_person'      => 'Hendra Wijaya',
            'contact_position'    => 'Fleet Supervisor',
            'contact_phone'       => '+62 818-2233-4455',
            'contact_email'       => 'hendra@ciptabangun.co.id',
            'contact_whatsapp'    => '+62 818-2233-4455',
            'status'              => 'inactive',
            'rating'              => 3.5,
            'total_transactions'  => 2,
            'total_spent'         => 280000000,
            'registered_date'     => '2023-11-05 12:00:00',
            'last_contact'        => '2024-02-14 11:30:00',
        ],
        [
            'customer_id'         => 'CUST-231220',
            'name'                => 'Anisa Permata',
            'email'               => 'anisa@suksesmandiri.com',
            'phone'               => '+62 857-1122-3344',
            'company'             => 'PT Sukses Mandiri',
            'industry'            => 'Construction',
            'city'                => 'Manado',
            'province'            => 'Sulawesi Utara',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Sam Ratulangi No. 30, Manado, Sulawesi Utara 95111',
            'website'             => 'www.suksesmandiri.com',
            'npwp'                => '12.345.678.9-020.000',
            'contact_person'      => 'Anisa Permata',
            'contact_position'    => 'Finance Manager',
            'contact_phone'       => '+62 857-1122-3344',
            'contact_email'       => 'anisa@suksesmandiri.com',
            'contact_whatsapp'    => '+62 857-1122-3344',
            'status'              => 'active',
            'rating'              => 4.4,
            'total_transactions'  => 10,
            'total_spent'         => 1950000000,
            'registered_date'     => '2023-12-20 09:00:00',
            'last_contact'        => '2024-05-29 14:45:00',
        ],
        [
            'customer_id'         => 'CUST-240110',
            'name'                => 'Tony Saputra',
            'email'               => 'tony@jayaabadi.co.id',
            'phone'               => '+62 878-5566-7788',
            'company'             => 'CV Jaya Abadi',
            'industry'            => 'Mining',
            'city'                => 'Banjarmasin',
            'province'            => 'Kalimantan Selatan',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Pangeran Antasari No. 18, Banjarmasin, Kalimantan Selatan 70111',
            'website'             => 'www.jayaabadi.co.id',
            'npwp'                => '13.456.789.0-021.000',
            'contact_person'      => 'Tony Saputra',
            'contact_position'    => 'Direktur Utama',
            'contact_phone'       => '+62 878-5566-7788',
            'contact_email'       => 'tony@jayaabadi.co.id',
            'contact_whatsapp'    => '+62 878-5566-7788',
            'status'              => 'active',
            'rating'              => 4.0,
            'total_transactions'  => 3,
            'total_spent'         => 550000000,
            'registered_date'     => '2024-01-10 08:30:00',
            'last_contact'        => '2024-05-15 10:00:00',
        ],
        [
            'customer_id'         => 'CUST-240205',
            'name'                => 'Ratna Sari',
            'email'               => 'ratna@multiteknik.co.id',
            'phone'               => '+62 812-9988-7766',
            'company'             => 'PT Multi Teknik',
            'industry'            => 'Construction',
            'city'                => 'Denpasar',
            'province'            => 'Bali',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Sunset Road No. 25, Denpasar, Bali 80234',
            'website'             => 'www.multiteknik.co.id',
            'npwp'                => '14.567.890.1-022.000',
            'contact_person'      => 'Ratna Sari',
            'contact_position'    => 'Technical Director',
            'contact_phone'       => '+62 812-9988-7766',
            'contact_email'       => 'ratna@multiteknik.co.id',
            'contact_whatsapp'    => '+62 812-9988-7766',
            'status'              => 'active',
            'rating'              => 4.8,
            'total_transactions'  => 11,
            'total_spent'         => 2680000000,
            'registered_date'     => '2024-02-05 07:00:00',
            'last_contact'        => '2024-05-31 08:30:00',
        ],
        [
            'customer_id'         => 'CUST-240315',
            'name'                => 'Dimas Aditya',
            'email'               => 'dimas@bintangmas.com',
            'phone'               => '+62 856-3344-5566',
            'company'             => 'CV Bintang Mas',
            'industry'            => 'Infrastructure',
            'city'                => 'Solo',
            'province'            => 'Jawa Tengah',
            'country'             => 'Indonesia',
            'address'             => 'Jl. Slamet Riyadi No. 42, Solo, Jawa Tengah 57111',
            'website'             => 'www.bintangmas.com',
            'npwp'                => '15.678.901.2-023.000',
            'contact_person'      => 'Dimas Aditya',
            'contact_position'    => 'Project Manager',
            'contact_phone'       => '+62 856-3344-5566',
            'contact_email'       => 'dimas@bintangmas.com',
            'contact_whatsapp'    => '+62 856-3344-5566',
            'status'              => 'active',
            'rating'              => 3.9,
            'total_transactions'  => 4,
            'total_spent'         => 720000000,
            'registered_date'     => '2024-03-15 11:15:00',
            'last_contact'        => '2024-05-27 16:00:00',
        ],
    ];

    $inserted = 0;

    foreach ($dummy_data as $data) {
        $result = $wpdb->insert($table_name, $data);
        if ($result) {
            $inserted++;
        }
    }

    return "Successfully inserted {$inserted} customer dummy records.";
}

// Auto-run if accessed directly
if (php_sapi_name() === 'cli' || (isset($_GET['run_dummy']) && $_GET['run_dummy'] === 'customers')) {
    add_action('init', function() {
        echo gti_insert_dummy_customers();
    });
}
